name: Docker

on:
  workflow_call:
    secrets:
      GOLANG_VERSION:
        required: true
        description: "Golang version to use."
      GOMODULE_PRIVATE_KEY:
        required: false
        description: "SSH key that has permission to access private Go modules."

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code."
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: shopnap/setup-go@main
        with:
          go-version: ${{ secrets.GOLANG_VERSION }}
          private-key: ${{ secrets.GOMODULE_PRIVATE_KEY }}

      - name: "Download dependencies."
        run: make dependencies

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Docker build"
        run: make docker-build TAG=github-workflow-test-image

      - name: "Docker dry run"
        run: make docker-dryrun TAG=github-workflow-test-image
